### ISSUE TITLE
Is it possible to have TOC include some headings from the md file?

### ISSUE THREAD

**Issue by stratus-ss** [abhinav/stitchmd#134]
Let's say I have a summary file like this

```
- [Installing The Operators](rhoai_installing_operators.md)
    - [Installing The NVIDIA GPU Operator](blank.md)
        - [NVIDIA Cluster Monitoring](nvidia_cluster_monitoring_cli.md)
```

Inside Cluster Monitoring I have 3 different headings in the file itself:

```
## Enabling Monitoring Dashboard

<stuff> ...

## Enabling The NVIDIA GPU Operator Dashboard

<stuff> ...

## Using NVIDIA SMI

<stuff> ...
```

The headings work exactly as I expect when `stitchmd` does it's thing. In wiki software you can do things like include a maximum depth included in the TOC so that you can say have an H3 be included by not H4 +. 

I know I could break these sections into their own file and include those in the summary to accomplish the same. But instead of having to break up files into tiny ones, I was wondering if it is possible to do the above? You can see my doc example [here](https://github.com/stratus-ss/openshift-ai/blob/main/docs/rendered/OpenShift_AI_CLI.md#nvidia-cluster-monitoring)

I'd like to see:

```
* Installing The Operators
  * Installing the NVIDIA GPU Operator
    * NVIDIA Cluster Monitoring
      * Enabling Monitoring Dashboard
      * Enabling The NVIDIA GPU Operator Dashboard
      * Using NVIDIA SMI
```
In the TOC

**Comment by abhinav** [comment]
Hello, @stratus-ss. Thanks for the report.
Yes, this was something I left room to add in the future when frontmatter support was developed.
I had a minute this weekend to work on this: #143

**Comment by stratus-ss** [comment]
Just wanted to say thank you. I really enjoy this tool you have created!
